project:
  type: website
  output-dir: docs

website:
  title: "Informes de análisis de algoritmos"
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Unidad 1"
        href: Unidad_1.ipynb
      - text: "Unidad 2"
        href: Unidad_2.ipynb
      - text: "Unidad 3"
        href: Unidad_3.ipynb
      - text: "Unidad 4"
        href: Unidad_4.ipynb
      - text: "Unidad 5"
        href: Unidad_5.ipynb

format:
  html:
    theme: cosmo
    toc: true
    lang: es
